version: '3'

services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
    image: nextjs
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - app-next
    volumes:
      - .:/app

networks:
  app-next:
    driver: bridge